<?php
use PhpOffice\PhpSpreadsheet\Spreadsheet;
use PhpOffice\PhpSpreadsheet\Writer\Xlsx;
require '../../iwesStatic.php';
use Aws\S3\S3Client;
use Aws\Common\Credentials\Credentials;
\Monkey::app()->vendorLibraries->load('spreadsheet');
$xlsContentFilePath = '/media/sf_sites/iwespro/temp/hello world.xlsx';
$spreadsheet = new Spreadsheet();
$sheet = $spreadsheet->getActiveSheet();
$sheet->setCellValue('A1', 'TemplateType=fptcustom');
$sheet->setCellValue('B1', 'Version=2021.1115');
$sheet->setCellValue('C1', 'TemplateSignature=U0hPRVM=');
$sheet->setCellValue('D1', 'settings=contentLanguageTag=it_IT&feedType=610841&headerLanguageTag=it_IT&primaryMarketplaceId=amzn1.mp.o.APJ6JRA9NG5V4&templateIdentifier=41a25e32-8f53-4fb5-9cd8-7b5e03a525e1&timestamp=2021-11-15T20%3A47%3A38.259Z');
$sheet->setCellValue('E1', 'Le prime 3 righe sono destinate a uso esclusivo di Amazon.com. Non modificare o eliminare le prime 3 righe.');
$sheet->setCellValue('U1', 'Immagini');
$sheet->setCellValue('AE1', 'Varianti');
$sheet->setCellValue('AI1', 'Di base');
$sheet->setCellValue('BJ1', 'Scoperta');
$sheet->setCellValue('CZ1', 'Arricchimento del prodotto');
$sheet->setCellValue('DE1', 'Mappatura altezza calzatura');
$sheet->setCellValue('DT1', 'Metodo di gestione');
$sheet->setCellValue('EC1', 'Conformità');
$sheet->setCellValue('FO2', 'Offerta');
$sheet->setCellValue('GJ1', 'Offerta (IT, UK, DE, FR, ES, NL)');


$sheet->setCellValue('A2', 'Tipo di prodotto');
$sheet->setCellValue('B2', 'SKU venditore');
$sheet->setCellValue('C2', 'Marca');
$sheet->setCellValue('D2', 'Codice prodotto standard');
$sheet->setCellValue('E2', 'Tipo codice prodotto');
$sheet->setCellValue('F2', 'Titolo articolo');
$sheet->setCellValue('G2', 'Browse node raccomandato');
$sheet->setCellValue('H2', 'Materiale esterno');
$sheet->setCellValue('I2', 'Sistema di taglie calazutre');
$sheet->setCellValue('J2', 'Fascia d\'età per taglia scarpa');
$sheet->setCellValue('K2', 'Tipologia di taglia scarpa');
$sheet->setCellValue('L2', 'Largezza scarpa');
$sheet->setCellValue('M2', 'Taglia scarpa');
$sheet->setCellValue('N2', 'Colore');
$sheet->setCellValue('O2', 'Mappatura colore');
$sheet->setCellValue('P2', 'Paese/Regione di origine');
$sheet->setCellValue('Q2', 'Quantità');
$sheet->setCellValue('R2', 'URL immagine principale');
$sheet->setCellValue('S2', 'Sesso');
$sheet->setCellValue('T2', 'Descrizione fascia d\'étà');
$sheet->setCellValue('U2', 'URL altre immagini1');
$sheet->setCellValue('V2', 'URL altre immagini2');
$sheet->setCellValue('W2', 'URL altre immagini3');
$sheet->setCellValue('X2', 'URL altre immagini4');
$sheet->setCellValue('Y2', 'URL altre immagini5');
$sheet->setCellValue('Z2', 'URL altre immagini6');
$sheet->setCellValue('AA2', 'URL altre immagini7');
$sheet->setCellValue('AB2', 'URL altre immagini8');
$sheet->setCellValue('AC2', 'URL altre immagini');
$sheet->setCellValue('AD2', 'URL immagine campione');
$sheet->setCellValue('AE2', 'Parentela');
$sheet->setCellValue('AF2', 'SKU "parent"');
$sheet->setCellValue('AG2', 'Tipo di relazione');
$sheet->setCellValue('AI2', 'Aggiornamento - Eliminazione');
$sheet->setCellValue('AJ2', 'Produttore');
$sheet->setCellValue('AK2', 'Descrizione articolo');
$sheet->setCellValue('AL2', 'Anno del modello');
$sheet->setCellValue('AM2', 'Codice articolo del produttore');
$sheet->setCellValue('AN2', 'Numero di modello');
$sheet->setCellValue('AO2', 'Nome modello');
$sheet->setCellValue('AP2', 'Materiale interno');
$sheet->setCellValue('AO2', 'Materiale suola');
$sheet->setCellValue('AP2', 'Materiale interno');
$sheet->setCellValue('AQ2', 'Materiale suola');
$sheet->setCellValue('AR2', 'Tipo di tacco');
$sheet->setCellValue('AS2', 'Altezza tacco');
$sheet->setCellValue('AT2', 'Tipo di chiusura');
$sheet->setCellValue('AU2', 'footwear_gender');
$sheet->setCellValue('AV2', 'footwear_width_unisex');
$sheet->setCellValue('AW2', 'footwear_to_size_unisex');
$sheet->setCellValue('AX2', 'Indice di temperatura');
$sheet->setCellValue('AY2', 'Motivo esenzione GTIN');
$sheet->setCellValue('AZ2', 'Lingua');
$sheet->setCellValue('BA2', 'Lingua');
$sheet->setCellValue('BB2', 'Lingua');
$sheet->setCellValue('BC2', 'Lingua');
$sheet->setCellValue('BD2', 'Lingua');
$sheet->setCellValue('BE2', 'footwear_gender_unisex');
$sheet->setCellValue('BF2', 'Unità di misura dimensioni scarpa');
$sheet->setCellValue('BG2', 'footwear_size_unisex');
$sheet->setCellValue('BH2', 'Altezza del tacco');
$sheet->setCellValue('BI2', 'Taglia massima scapra (se range di taglie)');
$sheet->setCellValue('BJ2', 'Stile della punta');
$sheet->setCellValue('BK2', 'Caratteristica speciale');
$sheet->setCellValue('BL2', 'Caratteristica speciale');
$sheet->setCellValue('BM2', 'Caratteristica speciale');
$sheet->setCellValue('BN2', 'Caratteristica speciale');
$sheet->setCellValue('BP2', 'Occasione');
$sheet->setCellValue('BQ2', 'Tipo di materiale');
$sheet->setCellValue('BR2', 'Funzionalità principali');
$sheet->setCellValue('BS2', 'Funzionalità principali');
$sheet->setCellValue('BT2', 'Funzionalità principali');
$sheet->setCellValue('BU2', 'Funzionalità principali');
$sheet->setCellValue('BV2', 'Funzionalità principali');
$sheet->setCellValue('BW2', 'Termini di ricerca');
$sheet->setCellValue('BX2', 'platinum-keywords1-5');
$sheet->setCellValue('BY2', 'platinum-keywords1-5');
$sheet->setCellValue('BZ2', 'platinum-keywords1-5');
$sheet->setCellValue('CA2', 'platinum-keywords1-5');
$sheet->setCellValue('CB2', 'platinum-keywords1-5');
$sheet->setCellValue('CC2', 'Stile');
$sheet->setCellValue('CD2', 'Collezione');
$sheet->setCellValue('CE2', 'Stagione');
$sheet->setCellValue('CF2', 'Tipo di arco plantare');
$sheet->setCellValue('CG2', 'Resistenza all\'acqua');
$sheet->setCellValue('CH2', 'Correzione pronazione');
$sheet->setCellValue('CI2', 'Tipo di sport');
$sheet->setCellValue('CJ2', 'Imbottitura');
$sheet->setCellValue('CK2', 'Nome del tipo di articolo');
$sheet->setCellValue('CL2', 'Motivo');
$sheet->setCellValue('CM2', 'target_audience_keywords1');
$sheet->setCellValue('CN2', 'target_audience_keywords2');
$sheet->setCellValue('CO2', 'target_audience_keywords3');
$sheet->setCellValue('CP2', 'target_audience_keywords4');
$sheet->setCellValue('CQ2', 'target_audience_keywords5');
$sheet->setCellValue('CR2', 'Descrizione della pelliccia');
$sheet->setCellValue('CS2', 'shaft_style_type');
$sheet->setCellValue('CT2', 'Tipo di fornitura del ciclo di vita del prodotto');
$sheet->setCellValue('CT2', 'Tipo di fornitura del ciclo di vita del prodotto');
$sheet->setCellValue('CU2', 'Tipo di fornitura del ciclo di vita del prodotto');
$sheet->setCellValue('CV2', 'Tipo di fornitura del ciclo di vita del prodotto');
$sheet->setCellValue('CW2', 'Tipo di fornitura del ciclo di vita del prodotto');
$sheet->setCellValue('CX2', 'Tipo di fornitura del ciclo di vita del prodotto');
$sheet->setCellValue('CY2', 'Data di prenotazione articolo');
$sheet->setCellValue('CZ2', 'Tipo di cinghia');
$sheet->setCellValue('DA2', 'Composizione materiale');
$sheet->setCellValue('DB2', 'Tipo di soletta');
$sheet->setCellValue('DC2', 'Tipo di pelle');
$sheet->setCellValue('DD2', 'Superficie consigliata');
$sheet->setCellValue('DE2', 'Mappatura altezza calzatura');
$sheet->setCellValue('DF2', 'Unità di misura peso di spedizione');
$sheet->setCellValue('DG2', 'Peso di spedizione');
$sheet->setCellValue('DH2', 'Lunghezza articolo');
$sheet->setCellValue('DI2', 'Altezza articolo');
$sheet->setCellValue('DJ2', 'Larghezza articolo');
$sheet->setCellValue('DK2', 'Altezza gambale');
$sheet->setCellValue('DL2', 'Altezza della suola');
$sheet->setCellValue('DM2', 'Larghezza Scarpa');
$sheet->setCellValue('DN2', 'unitàdimisuraaltezzadell\'asta');
$sheet->setCellValue('DO2', 'Unità di misura larghezza del prodotto');
$sheet->setCellValue('DP2', 'Forma della montatura');
$sheet->setCellValue('DQ2', 'Unità di misura altezza del prodotto');
$sheet->setCellValue('DR2', 'shoe_width_unit_of_measure');
$sheet->setCellValue('DS2', 'Unità di misura lunghezza del prodotto');
$sheet->setCellValue('DT2', 'Altezza pacco');
$sheet->setCellValue('DU2', 'Larghezza pacco');
$sheet->setCellValue('DV2', 'Lunghezza pacco');
$sheet->setCellValue('DW2', 'Peso pacco');
$sheet->setCellValue('DX2', 'Unità di misura peso collo');
$sheet->setCellValue('DZ2', 'Unità di misura lunghezza collo');
$sheet->setCellValue('EA2', 'Unità di misura delle dimensioni del collo');
$sheet->setCellValue('EB2', 'Unità di misura larghezza collo');
$sheet->setCellValue('EC2', 'Batterie incluse?');
$sheet->setCellValue('ED2', 'Composizione della batteria');
$sheet->setCellValue('EE2', 'Contenuto di litio (grammi)');
$sheet->setCellValue('EF2', 'Peso batteria');
$sheet->setCellValue('EG2', 'Peso Articolo');
$sheet->setCellValue('EH2', 'item_weight_unit_of_measure');
$sheet->setCellValue('EI2', 'Direttiva UE sulla sicurezza dei giocattoli - avvertenze non relative alle fasce d\'età');
$sheet->setCellValue('EJ2', 'Il prodotto è una batteria o utilizza batterie?');
$sheet->setCellValue('EK2', 'Tipo/dimensione batteria');
$sheet->setCellValue('EL2', 'Tipo/dimensione batteria');
$sheet->setCellValue('EL2', 'Tipo/dimensione batteria');
$sheet->setCellValue('EN2', 'Numero di batterie');
$sheet->setCellValue('EO2', 'Numero di batterie');
$sheet->setCellValue('EP2', 'Numero di batterie');
$sheet->setCellValue('EQ2', 'battery_weight_unit_of_measure');
$sheet->setCellValue('ER2', 'Numero di celle di litio (metallo)');
$sheet->setCellValue('ES2', 'Nume celle di litio (ioni)');
$sheet->setCellValue('ET2', 'Confezione batteria al litio');
$sheet->setCellValue('EU2', 'Wattora per batteria');
$sheet->setCellValue('EV2', 'lithium_battery_energy_content_unit_of_measure');
$sheet->setCellValue('EW2', 'lithium_battery_weight_unit_of_measure');
$sheet->setCellValue('EX2', 'Regolamenti relativi a merci pericolose applicabili');
$sheet->setCellValue('EY2', 'Regolamenti relativi a merci pericolose applicabili');
$sheet->setCellValue('EZ2', 'Regolamenti relativi a merci pericolose applicabili');
$sheet->setCellValue('FA2', 'Regolamenti relativi a merci pericolose applicabili');
$sheet->setCellValue('FB2', 'Regolamenti relativi a merci pericolose applicabili');
$sheet->setCellValue('FC2', 'Numero ONU');
$sheet->setCellValue('FD2', 'URL scheda di dati di sicurezza (SDS)');
$sheet->setCellValue('FE2', 'Volume');
$sheet->setCellValue('FG2', 'is_adult_product');
$sheet->setCellValue('FH2', 'Punto di infiammabilità (°C)?');
$sheet->setCellValue('FI2', 'Regolamentazione del materiale dichiarata dal fornitore');
$sheet->setCellValue('FJ2', 'Regolamentazione del materiale dichiarata dal fornitore');
$sheet->setCellValue('FK2', 'Regolamentazione del materiale dichiarata dal fornitore');
$sheet->setCellValue('FL2', 'Classificazione/pittogrammi GHS (seleziona tutti quelli applicabili)');
$sheet->setCellValue('FM2', 'Classificazione/pittogrammi GHS (seleziona tutti quelli applicabili)');
$sheet->setCellValue('FN2', 'Classificazione/pittogrammi GHS (seleziona tutti quelli applicabili)');
$sheet->setCellValue('FO2', 'Tipo condizioni offerta');
$sheet->setCellValue('FP2', 'Nota sulle condizioni dell\'offerta');
$sheet->setCellValue('FQ2', 'Prezzo di listino');
$sheet->setCellValue('FR2', 'Codice fiscale prodotto');
$sheet->setCellValue('FS2', 'Data di rilascio');
$sheet->setCellValue('FT2', 'Data di riassortimento');
$sheet->setCellValue('FU2', 'Quantità prodotti per ordine');
$sheet->setCellValue('FV2', 'Disponibilità messaggio auguri');
$sheet->setCellValue('FW2', 'Disponibilità confezione regalo');
$sheet->setCellValue('FX2', 'Produzione interrotta');
$sheet->setCellValue('FY2', 'tempo di gestione');
$sheet->setCellValue('FZ2', 'Prodotto soggetto a scadenza');
$sheet->setCellValue('GA2', 'Prezzo di listino con tasse');
$sheet->setCellValue('GB2', 'Tipo di scadenza del prodotto');
$sheet->setCellValue('GC2', 'Numero di articoli.');
$sheet->setCellValue('GD2', 'Durata di conservazione all\'interno del Centro Logistico di Amazon');
$sheet->setCellValue('GF2', 'Massima Quantità Ordinabile');
$sheet->setCellValue('GE2', 'Gruppo Spedizione venditore');
$sheet->setCellValue('GG2', 'Vendita delle Unità Rimanenti');
$sheet->setCellValue('GH2', 'Prezzo consigliato');
$sheet->setCellValue('GI2', 'Quantità di Ordine Minimo');
$sheet->setCellValue('GJ2', 'Data di fine vendita (IT)');
$sheet->setCellValue('GK2', 'Data di inizio della vendita (IT)');
$sheet->setCellValue('GL2', 'Prezzo di vendita EUR (IT)');
$sheet->setCellValue('GM2', 'Data interruzione della vendita (IT)');
$sheet->setCellValue('GN2', 'Prezzo EUR (IT)');
$sheet->setCellValue('GO2', 'Data di inizio dell\'offerta (IT)');
$sheet->setCellValue('GP2', 'Data di fine vendita (UK)');
$sheet->setCellValue('GQ2', 'Data di inizio della vendita (UK)');
$sheet->setCellValue('GR2', 'Prezzo di vendita GBP (UK)');
$sheet->setCellValue('GS2', 'Data interruzione della vendita (UK)');
$sheet->setCellValue('GT2', 'Prezzo GBP (UK)');
$sheet->setCellValue('GU2', 'Data di inizio dell\'offerta (UK)');
$sheet->setCellValue('GV2', 'Data di fine vendita (DE)');
$sheet->setCellValue('GW2', 'Data di inizio della vendita (DE)');
$sheet->setCellValue('GX2', 'Prezzo di vendita EUR (DE)');
$sheet->setCellValue('GY2', 'Data interruzione della vendita (DE)');
$sheet->setCellValue('GZ2', 'Prezzo EUR (DE)');
$sheet->setCellValue('HA2', 'Data di inizio dell\'offerta (DE)');
$sheet->setCellValue('HB2', 'Data di fine vendita (FR)');
$sheet->setCellValue('HC2', 'Data di inizio della vendita (FR)');
$sheet->setCellValue('HD2', 'Prezzo di vendita EUR (FR)');
$sheet->setCellValue('HE2', 'Data interruzione della vendita (FR)');
$sheet->setCellValue('HF2', 'Prezzo EUR (FR)');
$sheet->setCellValue('HG2', 'Data di inizio dell\'offerta (FR)');
$sheet->setCellValue('HH2', 'Data di fine vendita (ES)');
$sheet->setCellValue('HI2', 'Data di inizio della vendita (ES)');
$sheet->setCellValue('HJ2', 'Prezzo di vendita EUR (ES)');
$sheet->setCellValue('HK2', 'Data interruzione della vendita (ES)');
$sheet->setCellValue('HL2', 'Prezzo EUR (ES)');
$sheet->setCellValue('HM2', 'Data di inizio dell\'offerta (ES)');
$sheet->setCellValue('HN2', 'Data di fine vendita (NL)');
$sheet->setCellValue('HO2', 'Data di inizio della vendita (NL)');
$sheet->setCellValue('HP2', 'Prezzo di vendita EUR (NL)');
$sheet->setCellValue('HQ2', 'Data interruzione della vendita (NL)');
$sheet->setCellValue('HR2', 'Prezzo EUR (NL)');
$sheet->setCellValue('HS2', 'Data di inizio dell\'offerta (NL)');
$sheet->setCellValue('A3', 'Tipo di prodotto');
$sheet->setCellValue('B3', 'SKU venditore');
$sheet->setCellValue('C3', 'Marca');
$sheet->setCellValue('D3', 'Codice prodotto standard');
$sheet->setCellValue('E3', 'Tipo codice prodotto');
$sheet->setCellValue('F3', 'Titolo articolo');
$sheet->setCellValue('G3', 'Browse node raccomandato');
$sheet->setCellValue('H3', 'Materiale esterno');
$sheet->setCellValue('I3', 'Sistema di taglie calazutre');
$sheet->setCellValue('J3', 'Fascia d\'età per taglia scarpa');
$sheet->setCellValue('K3', 'Tipologia di taglia scarpa');
$sheet->setCellValue('L3', 'Largezza scarpa');
$sheet->setCellValue('M3', 'Taglia scarpa');
$sheet->setCellValue('N3', 'Colore');
$sheet->setCellValue('O3', 'Mappatura colore');
$sheet->setCellValue('P3', 'Paese/Regione di origine');
$sheet->setCellValue('Q3', 'Quantità');
$sheet->setCellValue('R3', 'URL immagine principale');
$sheet->setCellValue('S3', 'Sesso');
$sheet->setCellValue('T3', 'Descrizione fascia d\'étà');
$sheet->setCellValue('U3', 'URL altre immagini1');
$sheet->setCellValue('V3', 'URL altre immagini2');
$sheet->setCellValue('W3', 'URL altre immagini3');
$sheet->setCellValue('X3', 'URL altre immagini4');
$sheet->setCellValue('Y3', 'URL altre immagini5');
$sheet->setCellValue('Z3', 'URL altre immagini6');
$sheet->setCellValue('AA3', 'URL altre immagini7');
$sheet->setCellValue('AB3', 'URL altre immagini8');
$sheet->setCellValue('AC3', 'URL altre immagini');
$sheet->setCellValue('AD3', 'URL immagine campione');
$sheet->setCellValue('AE3', 'Parentela');
$sheet->setCellValue('AF3', 'SKU "parent"');
$sheet->setCellValue('AG3', 'Tipo di relazione');
$sheet->setCellValue('AI3', 'Aggiornamento - Eliminazione');
$sheet->setCellValue('AJ3', 'Produttore');
$sheet->setCellValue('AK3', 'Descrizione articolo');
$sheet->setCellValue('AL3', 'Anno del modello');
$sheet->setCellValue('AM3', 'Codice articolo del produttore');
$sheet->setCellValue('AN3', 'Numero di modello');
$sheet->setCellValue('AO3', 'Nome modello');
$sheet->setCellValue('AP3', 'Materiale interno');
$sheet->setCellValue('AO3', 'Materiale suola');
$sheet->setCellValue('AP3', 'Materiale interno');
$sheet->setCellValue('AQ3', 'Materiale suola');
$sheet->setCellValue('AR3', 'Tipo di tacco');
$sheet->setCellValue('AS3', 'Altezza tacco');
$sheet->setCellValue('AT3', 'Tipo di chiusura');
$sheet->setCellValue('AU3', 'footwear_gender');
$sheet->setCellValue('AV3', 'footwear_width_unisex');
$sheet->setCellValue('AW3', 'footwear_to_size_unisex');
$sheet->setCellValue('AX3', 'Indice di temperatura');
$sheet->setCellValue('AY3', 'Motivo esenzione GTIN');
$sheet->setCellValue('AZ3', 'Lingua');
$sheet->setCellValue('BA3', 'Lingua');
$sheet->setCellValue('BB3', 'Lingua');
$sheet->setCellValue('BC3', 'Lingua');
$sheet->setCellValue('BD3', 'Lingua');
$sheet->setCellValue('BE3', 'footwear_gender_unisex');
$sheet->setCellValue('BF3', 'Unità di misura dimensioni scarpa');
$sheet->setCellValue('BG3', 'footwear_size_unisex');
$sheet->setCellValue('BH3', 'Altezza del tacco');
$sheet->setCellValue('BI3', 'Taglia massima scapra (se range di taglie)');
$sheet->setCellValue('BJ3', 'Stile della punta');
$sheet->setCellValue('BK3', 'Caratteristica speciale');
$sheet->setCellValue('BL2', 'Caratteristica speciale');
$sheet->setCellValue('BM2', 'Caratteristica speciale');
$sheet->setCellValue('BN2', 'Caratteristica speciale');
$sheet->setCellValue('BP2', 'Occasione');
$sheet->setCellValue('BQ2', 'Tipo di materiale');
$sheet->setCellValue('BR2', 'Funzionalità principali');
$sheet->setCellValue('BS2', 'Funzionalità principali');
$sheet->setCellValue('BT2', 'Funzionalità principali');
$sheet->setCellValue('BU2', 'Funzionalità principali');
$sheet->setCellValue('BV2', 'Funzionalità principali');
$sheet->setCellValue('BW2', 'Termini di ricerca');
$sheet->setCellValue('BX2', 'platinum-keywords1-5');
$sheet->setCellValue('BY2', 'platinum-keywords1-5');
$sheet->setCellValue('BZ2', 'platinum-keywords1-5');
$sheet->setCellValue('CA2', 'platinum-keywords1-5');
$sheet->setCellValue('CB2', 'platinum-keywords1-5');
$sheet->setCellValue('CC2', 'Stile');
$sheet->setCellValue('CD2', 'Collezione');
$sheet->setCellValue('CE2', 'Stagione');
$sheet->setCellValue('CF2', 'Tipo di arco plantare');
$sheet->setCellValue('CG2', 'Resistenza all\'acqua');
$sheet->setCellValue('CH2', 'Correzione pronazione');
$sheet->setCellValue('CI2', 'Tipo di sport');
$sheet->setCellValue('CJ2', 'Imbottitura');
$sheet->setCellValue('CK2', 'Nome del tipo di articolo');
$sheet->setCellValue('CL2', 'Motivo');
$sheet->setCellValue('CM2', 'target_audience_keywords1');
$sheet->setCellValue('CN2', 'target_audience_keywords2');
$sheet->setCellValue('CO2', 'target_audience_keywords3');
$sheet->setCellValue('CP2', 'target_audience_keywords4');
$sheet->setCellValue('CQ2', 'target_audience_keywords5');
$sheet->setCellValue('CR2', 'Descrizione della pelliccia');
$sheet->setCellValue('CS2', 'shaft_style_type');
$sheet->setCellValue('CT2', 'Tipo di fornitura del ciclo di vita del prodotto');
$sheet->setCellValue('CT2', 'Tipo di fornitura del ciclo di vita del prodotto');
$sheet->setCellValue('CU2', 'Tipo di fornitura del ciclo di vita del prodotto');
$sheet->setCellValue('CV2', 'Tipo di fornitura del ciclo di vita del prodotto');
$sheet->setCellValue('CW2', 'Tipo di fornitura del ciclo di vita del prodotto');
$sheet->setCellValue('CX2', 'Tipo di fornitura del ciclo di vita del prodotto');
$sheet->setCellValue('CY2', 'Data di prenotazione articolo');
$sheet->setCellValue('CZ2', 'Tipo di cinghia');
$sheet->setCellValue('DA2', 'Composizione materiale');
$sheet->setCellValue('DB2', 'Tipo di soletta');
$sheet->setCellValue('DC2', 'Tipo di pelle');
$sheet->setCellValue('DD2', 'Superficie consigliata');
$sheet->setCellValue('DE2', 'Mappatura altezza calzatura');
$sheet->setCellValue('DF2', 'Unità di misura peso di spedizione');
$sheet->setCellValue('DG2', 'Peso di spedizione');
$sheet->setCellValue('DH2', 'Lunghezza articolo');
$sheet->setCellValue('DI2', 'Altezza articolo');
$sheet->setCellValue('DJ2', 'Larghezza articolo');
$sheet->setCellValue('DK2', 'Altezza gambale');
$sheet->setCellValue('DL2', 'Altezza della suola');
$sheet->setCellValue('DM2', 'Larghezza Scarpa');
$sheet->setCellValue('DN2', 'unitàdimisuraaltezzadell\'asta');
$sheet->setCellValue('DO2', 'Unità di misura larghezza del prodotto');
$sheet->setCellValue('DP2', 'Forma della montatura');
$sheet->setCellValue('DQ2', 'Unità di misura altezza del prodotto');
$sheet->setCellValue('DR2', 'shoe_width_unit_of_measure');
$sheet->setCellValue('DS2', 'Unità di misura lunghezza del prodotto');
$sheet->setCellValue('DT2', 'Altezza pacco');
$sheet->setCellValue('DU2', 'Larghezza pacco');
$sheet->setCellValue('DV2', 'Lunghezza pacco');
$sheet->setCellValue('DW2', 'Peso pacco');
$sheet->setCellValue('DX2', 'Unità di misura peso collo');
$sheet->setCellValue('DZ2', 'Unità di misura lunghezza collo');
$sheet->setCellValue('EA2', 'Unità di misura delle dimensioni del collo');
$sheet->setCellValue('EB2', 'Unità di misura larghezza collo');
$sheet->setCellValue('EC2', 'Batterie incluse?');
$sheet->setCellValue('ED2', 'Composizione della batteria');
$sheet->setCellValue('EE2', 'Contenuto di litio (grammi)');
$sheet->setCellValue('EF2', 'Peso batteria');
$sheet->setCellValue('EG2', 'Peso Articolo');
$sheet->setCellValue('EH2', 'item_weight_unit_of_measure');
$sheet->setCellValue('EI2', 'Direttiva UE sulla sicurezza dei giocattoli - avvertenze non relative alle fasce d\'età');
$sheet->setCellValue('EJ2', 'Il prodotto è una batteria o utilizza batterie?');
$sheet->setCellValue('EK2', 'Tipo/dimensione batteria');
$sheet->setCellValue('EL2', 'Tipo/dimensione batteria');
$sheet->setCellValue('EL2', 'Tipo/dimensione batteria');
$sheet->setCellValue('EN2', 'Numero di batterie');
$sheet->setCellValue('EO2', 'Numero di batterie');
$sheet->setCellValue('EP2', 'Numero di batterie');
$sheet->setCellValue('EQ2', 'battery_weight_unit_of_measure');
$sheet->setCellValue('ER2', 'Numero di celle di litio (metallo)');
$sheet->setCellValue('ES2', 'Nume celle di litio (ioni)');
$sheet->setCellValue('ET2', 'Confezione batteria al litio');
$sheet->setCellValue('EU2', 'Wattora per batteria');
$sheet->setCellValue('EV2', 'lithium_battery_energy_content_unit_of_measure');
$sheet->setCellValue('EW2', 'lithium_battery_weight_unit_of_measure');
$sheet->setCellValue('EX2', 'Regolamenti relativi a merci pericolose applicabili');
$sheet->setCellValue('EY2', 'Regolamenti relativi a merci pericolose applicabili');
$sheet->setCellValue('EZ2', 'Regolamenti relativi a merci pericolose applicabili');
$sheet->setCellValue('FA2', 'Regolamenti relativi a merci pericolose applicabili');
$sheet->setCellValue('FB2', 'Regolamenti relativi a merci pericolose applicabili');
$sheet->setCellValue('FC2', 'Numero ONU');
$sheet->setCellValue('FD2', 'URL scheda di dati di sicurezza (SDS)');
$sheet->setCellValue('FE2', 'Volume');
$sheet->setCellValue('FG2', 'is_adult_product');
$sheet->setCellValue('FH2', 'Punto di infiammabilità (°C)?');
$sheet->setCellValue('FI2', 'Regolamentazione del materiale dichiarata dal fornitore');
$sheet->setCellValue('FJ2', 'Regolamentazione del materiale dichiarata dal fornitore');
$sheet->setCellValue('FK2', 'Regolamentazione del materiale dichiarata dal fornitore');
$sheet->setCellValue('FL2', 'Classificazione/pittogrammi GHS (seleziona tutti quelli applicabili)');
$sheet->setCellValue('FM2', 'Classificazione/pittogrammi GHS (seleziona tutti quelli applicabili)');
$sheet->setCellValue('FN2', 'Classificazione/pittogrammi GHS (seleziona tutti quelli applicabili)');
$sheet->setCellValue('FO2', 'Tipo condizioni offerta');
$sheet->setCellValue('FP2', 'Nota sulle condizioni dell\'offerta');
$sheet->setCellValue('FQ2', 'Prezzo di listino');
$sheet->setCellValue('FR2', 'Codice fiscale prodotto');
$sheet->setCellValue('FS2', 'Data di rilascio');
$sheet->setCellValue('FT2', 'Data di riassortimento');
$sheet->setCellValue('FU2', 'Quantità prodotti per ordine');
$sheet->setCellValue('FV2', 'Disponibilità messaggio auguri');
$sheet->setCellValue('FW2', 'Disponibilità confezione regalo');
$sheet->setCellValue('FX2', 'Produzione interrotta');
$sheet->setCellValue('FY2', 'tempo di gestione');
$sheet->setCellValue('FZ2', 'Prodotto soggetto a scadenza');
$sheet->setCellValue('GA2', 'Prezzo di listino con tasse');
$sheet->setCellValue('GB2', 'Tipo di scadenza del prodotto');
$sheet->setCellValue('GC2', 'Numero di articoli.');
$sheet->setCellValue('GD2', 'Durata di conservazione all\'interno del Centro Logistico di Amazon');
$sheet->setCellValue('GF2', 'Massima Quantità Ordinabile');
$sheet->setCellValue('GE2', 'Gruppo Spedizione venditore');
$sheet->setCellValue('GG2', 'Vendita delle Unità Rimanenti');
$sheet->setCellValue('GH2', 'Prezzo consigliato');
$sheet->setCellValue('GI2', 'Quantità di Ordine Minimo');
$sheet->setCellValue('GJ2', 'Data di fine vendita (IT)');
$sheet->setCellValue('GK2', 'Data di inizio della vendita (IT)');
$sheet->setCellValue('GL2', 'Prezzo di vendita EUR (IT)');
$sheet->setCellValue('GM2', 'Data interruzione della vendita (IT)');
$sheet->setCellValue('GN2', 'Prezzo EUR (IT)');
$sheet->setCellValue('GO2', 'Data di inizio dell\'offerta (IT)');
$sheet->setCellValue('GP2', 'Data di fine vendita (UK)');
$sheet->setCellValue('GQ2', 'Data di inizio della vendita (UK)');
$sheet->setCellValue('GR2', 'Prezzo di vendita GBP (UK)');
$sheet->setCellValue('GS2', 'Data interruzione della vendita (UK)');
$sheet->setCellValue('GT2', 'Prezzo GBP (UK)');
$sheet->setCellValue('GU2', 'Data di inizio dell\'offerta (UK)');
$sheet->setCellValue('GV2', 'Data di fine vendita (DE)');
$sheet->setCellValue('GW2', 'Data di inizio della vendita (DE)');
$sheet->setCellValue('GX2', 'Prezzo di vendita EUR (DE)');
$sheet->setCellValue('GY2', 'Data interruzione della vendita (DE)');
$sheet->setCellValue('GZ2', 'Prezzo EUR (DE)');
$sheet->setCellValue('HA2', 'Data di inizio dell\'offerta (DE)');
$sheet->setCellValue('HB2', 'Data di fine vendita (FR)');
$sheet->setCellValue('HC2', 'Data di inizio della vendita (FR)');
$sheet->setCellValue('HD2', 'Prezzo di vendita EUR (FR)');
$sheet->setCellValue('HE2', 'Data interruzione della vendita (FR)');
$sheet->setCellValue('HF2', 'Prezzo EUR (FR)');
$sheet->setCellValue('HG2', 'Data di inizio dell\'offerta (FR)');
$sheet->setCellValue('HH2', 'Data di fine vendita (ES)');
$sheet->setCellValue('HI2', 'Data di inizio della vendita (ES)');
$sheet->setCellValue('HJ2', 'Prezzo di vendita EUR (ES)');
$sheet->setCellValue('HK2', 'Data interruzione della vendita (ES)');
$sheet->setCellValue('HL2', 'Prezzo EUR (ES)');
$sheet->setCellValue('HM2', 'Data di inizio dell\'offerta (ES)');
$sheet->setCellValue('HN2', 'Data di fine vendita (NL)');
$sheet->setCellValue('HO2', 'Data di inizio della vendita (NL)');
$sheet->setCellValue('HP2', 'Prezzo di vendita EUR (NL)');
$sheet->setCellValue('HQ2', 'Data interruzione della vendita (NL)');
$sheet->setCellValue('HR2', 'Prezzo EUR (NL)');
$sheet->setCellValue('HS2', 'Data di inizio dell\'offerta (NL)');




$writer = new Xlsx($spreadsheet);
$writer->save($xlsContentFilePath);